create table "TITLES" ("IMDB_ID" VARCHAR(254) NOT NULL,"YEAR" INTEGER,"TITLE" VARCHAR(254),"MOVIE_TYPE" VARCHAR(254) NOT NULL,"POSTER_URL" VARCHAR(254),"SEASON" INTEGER,"NUMBER" INTEGER,"SERIES_IMDB_ID" VARCHAR(254),"ID" INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL);
create table "SUBTITLES" ("ID" VARCHAR(254) PRIMARY KEY NOT NULL,"IMDB_ID" VARCHAR(254) NOT NULL,"INDEXED" INTEGER NOT NULL);
create table "DOWNLOADS" ("TIME" TIMESTAMP NOT NULL);
create table "IMOVIE" ("OTHER_ID" INTEGER NOT NULL,"TITLE" VARCHAR(254) NOT NULL,"YEAR" INTEGER NOT NULL,"RATING" DECIMAL(21,2) NOT NULL,"VOTES" INTEGER NOT NULL,"SCORE" DECIMAL(21,2) NOT NULL,"GENRE" VARCHAR(254) NOT NULL,"POSTER" VARCHAR(254) NOT NULL,"TYPE" VARCHAR(254) NOT NULL,"IMDB_ID" VARCHAR(254) NOT NULL);
